#+SETUPFILE: setup.org
#+OPTIONS: num:t
#+AUTHOR: Martin R. Albrecht
#+TITLE: SIS with Hints Zoo
#+TODO: BROKEN | STANDARD EQUIVALENT
#+cite_export: csl ./apa-6th-edition.csl
#+bibliography: local.bib

#+BEGIN_HTML
\( 
  \newcommand\ring{\mathcal{R}}
  \newcommand\ZZ{\mathbb{Z}}
  \renewcommand{\vec}[1]{{\boldsymbol{\mathbf{#1}}}}
  \newcommand\mat[1]{\vec{#1}}
  \newcommand{\sample}{\gets_{\$}}
\)
#+END_HTML

An attempt to keep track of all those new SIS-like assumptions that hand out additional hints. Some of these venture into LWE land, but for now I want to keep it more or less SIS focused.

- *Designers:* Please consider whether you can re-use one of those many newfangled assumptions before introducing yet another one.

- *Cryptanalysts:* Analyse them!

In th jolly tradition of [[https://malb.io/are-graded-encoding-schemes-broken-yet.html]["Are Graded Encoding Schemes broken yet?"]]  I tag problems as BROKEN if I am aware of cryptanalysis. I also tag them as:

- STANDARD :: if there is a reduction from a standard (non-hint) assumption that covers meaningful parameters, i.e. those useful in applications. For example, k-SIS is tagged like this but k-R-ISIS is not because known reductions only cover parameters that, so far, seem useless in applications.

- EQUIVALENT :: if there is a reduction from another hint assumption. Again, this may only cover some parameters. This is meant to indicate that cryptanalytic efforts might be better directed at the equivalent problem.   

Please reach out if you find a mistake or have an update.

* STANDARD k-SIS

[cite:@PKC:BonFre11]

We give the module variant defined in [cite:@C:ACLMT22]. We recover the original definition by setting \(\ring := \ZZ\).

#+begin_quote
For any integer \(k \geq 0\), an instance of the k-M-SIS problem is a matrix \(\mat{A} \in \ring_{q}^{\eta \times \ell}\) and a set of \(k\) vectors \(\vec{u}_{0}, \ldots \vec{u}_{k-1}\) s.t. \(\mat{A}\cdot \vec{u}_{i} \equiv \vec{0} \bmod q\) with \(\|{\vec{u}_i}\| \leq \beta\). A solution to the problem is a nonzero vector \(\vec{u} \in \ring^{\ell}\) such that

\[\|{\vec{u}}\| \leq \beta^*, \quad \mat{A}\cdot \vec{u} \equiv \vec{0} \bmod q,\quad \text{and} \quad \vec{u} \notin \mathcal{K}\text{-}\operatorname{span}(\set{\vec{u}_i}_{0 \leq i < k}).\]
#+end_quote


An LWE variant, called k-LWE was introduced in [cite:@C:LPSS14].

** Hardness

The original paper showed that k-SIS (over \(\ZZ\)) is hard if SIS is hard for uniform \(\mat{A}\) and discrete Gaussian \(\vec{u}_{i}\). This reduction was improved in [cite:@C:LPSS14] to cover \(k = \mathcal{O}(\ell)\).

The condition \(\vec{u} \notin \mathcal{K}\text{-}\operatorname{span}(\set{\vec{u}_i}_{0 \leq i < k})\) can be dropped when \(k < \ell^{1/4}\) because then the probability that there is an additional short vector in the \(k\)-dimensional sublattice spanned by the \(\vec{u}_i\) is negligible.

No proof was provided for the module variant.

* One-more-ISIS

[cite:@CCS:AKSY22]

#+begin_quote
A challenger selects a matrix \(\mat{A} \in \ZZ_{q}^{\eta \times \ell}\) and sends it to the adversary. The adversary can perform two types of queries:

*Syndrome queries* The adversary can request a challenge vector which the challenger selects at random, i.e. \(\vec{t} \gets_{\$} \ZZ_{q}^{\eta}\), adds to some set \(\mathcal{S}\) and returns to the adversary.

*Preimage queries.* The adversary submits /any/ vector \(\vec{t}' \in \ZZ_{q}^{\eta}\). The challenger will return a short vector \(\vec{y}' \gets_{\$} D_{\ZZ^\ell,\sigma}\) such that \(\mat{A}\cdot \vec{y}' \equiv \vec{t}' \bmod q\). Denote \(k\) for the number of preimage queries.

In the end the adversary is asked to output \(k+1\) pairs \(\{(\vec{y}_i,\vec{t}_i)\}_{0 \leq i < k+1}\) satisfying:
\[\mat{A}\cdot \vec{y}_{i} \equiv \vec{t}_{i} \bmod q, \|\vec{y}_{i}\| \leq \beta \text{ and }\vec{t}_{i} \in \mathcal{S}.\]
#+end_quote

** Hardness

The hardness of the problem is analysed using direct cryptanalysis in the original paper. The authors give a combinatorial attack and a lattice attack.

*Combinatorial Attack.* The adversary requests \(\eta \cdot q\) preimages for all \(\{a \cdot \vec{e}_{i}\ \mid\ a \in \ZZ_{q}, i \in \ZZ_{\eta}\}\), here \(\vec{e}_{i}\) is the \(i\)-th unit vector. Then, adding up \(n\) such preimages allows to construct any image. Since the norm of the preimages returned by the challenger is \(\sqrt{\ell} \cdot \sigma\), this allows to solve the One-more-ISIS problem when \(\sqrt{n\cdot \ell} \cdot \sigma \leq \beta\). Of course, smaller and larger sets of preimages are possible, increasing and decreasing the output norm respectively.

*Lattice Attack.* The adversary requests \(\geq \ell\) preimages of zero and uses that to produce a short basis \(\mat{T}\) for the kernel of \(\mat{A}\), i.e. \(\mat{A}\cdot\mat{T} \equiv \vec{0} \bmod q\). This constitutes a trapdoor for \(\mat{A}\) and thus permits to return short preimages for any target. The key point here is that this trapdoor is of degraded quality relative to the trapdoor used by the challenger. The key computational challenge then is to fix-up or improve this degraded trapdoor in order to be able to sample sufficiently short vectors.

* K-R-ISIS

[cite:@C:ACLMT22]

#+begin_quote
Let \(g(\vec{X}) \in \mathcal{R}(\vec{X})\) be a Laurent monomial, i.e. \(g(\vec{X}) = \vec{X}^{\vec{e}} := \prod_{i \in \ZZ_w} X_i^{e_i}\) for some exponent vector \(\vec{e} = (e_i: i \in \ZZ_w) \in \ZZ^w\). Let \(\mathcal{G} \subset \mathcal{R}(\vec{X})\) be a set of Laurent monomials with \(k := |\mathcal{G}|\). Let \(g^{\star} \in \mathcal{R}(\vec{X})\) be a target Laurent monomial. We call a family \(\mathcal{G}\)  /k-M-ISIS-admissible/ if
1. all \(g \in \mathcal{G}\) have constant degree, i.e. \(\|\vec{e}\|_{1} \in O(1)\);
2. all \(g \in \mathcal{G}\) are distinct, i.e. \(\mathcal{G}\) is not a multiset; and
3. \(0 \not\in\mathcal{G}\).

We call a family \((\mathcal{G}, g^*)\)  k-M-ISIS-admissible if \(\mathcal{G}\) is k-MISIS-admissible, \(g^*\) has constant degree, and \(g^* \notin \mathcal{G}\).

 \\

Now, let \(\vec{t} = (1,0,\ldots,0)\).
Let \(\mathcal{G} \subset \mathcal{R}(\vec{X})\) be a set of \(w\)-variate Laurent monomial.
Let \(g^{\star} \in \mathcal{R}(\vec{X})\) be a target Laurent monomial.
Let \((\mathcal{G},g^\star)\) be k-M-ISIS-admissible.
Let  \(\mat{A} \gets_{\$} \ring_q^{\eta \times \ell}\), \(\vec{v} \gets_{\$} (\ring_q^\star)^w\). The /K-M-ISIS/ assumption states that given \((\mat{A}, \vec{v}, \vec{t}, \{\vec{u}_{g}\})\) with \(\vec{u}_{g}\) short and
\[
g(\vec{v}) \cdot \vec{t} \equiv \mat{A}\cdot \vec{u}_{g} \bmod q
\]
it is hard to find a short \(\vec{u}_{g^*}\) and small \(s^{*}\) s.t.
\[
s^* \cdot g^{*}(\vec{v}) \cdot \vec{t} \equiv \mat{A} \cdot \vec{u}_{g^*} \bmod q.
\]
When \(\eta = 1\), i.e. when \(\mat{A}\) is just a vector, we call the problem /k-R-ISIS/.
#+end_quote

** Hardness

The hardness of the problem is analysed by the authors by providing some partial reductions, i.e. covering some special cases. These special cases are not interesting for applications. The authors show that

- k-R-ISIS (with \(g^{*} \equiv 1\)) is as hard as R-SIS when \(\ell > k\) or when the system generated by \(\mathcal{G}\) is efficiently invertible.
- k-M-ISIS is at least as hard as k-R-ISIS and that k-M-ISIS is a true generalisation of k-R-SIS.
-  \((\mathcal{G},g^*)\) is as hard as \((\mathcal{G},0)\) for any \(\mathcal{G}\), formalising the intuition that the non-homogeneous variant is no easier than the homogeneous variant.
- scaling \((\mathcal{G},g^*)\) multiplicatively by any non-zero Laurent monomial does not change the hardness, e.g. we may choose to normalise instances to \(g^{*} \equiv 1\).

The authors also explore direct cryptanalysis:
- a direct SIS attack on \(\mat{A}\).
- finding short \(\ZZ\)-linear combinations of \(\vec{u}_{i}\)
- finding \(\mathbb{Q}\)-linear combinations of \(\vec{u}_{i}\) that produce short images.

* BROKEN Knowledge K-R-ISIS

[cite:@C:ACLMT22]

The assumption essentially states that for any element \(c \cdot \vec{t}\) that the adversary can produce together with a short preimage, it produced that as some small linear combination of the preimages \(\{\vec{u}_{g}\}\) we have given it. Thus, roughly:
#+begin_quote
If an adversary outputs any \(c, \vec{u}_{c}\) s.t.
\[
c \cdot \vec{t} \equiv \mat{A} \cdot \vec{u}_{c} \bmod q
\]
then there is an extractor that -- with access to the adversary's randomness -- outputs short
\(\{c_{g}\}\) s.t.
\[
c \equiv \sum_{g \in \mathcal{G}} c_{g} \cdot g(\vec{v}) \bmod q.
\]
#+end_quote

The knowledge assumption only makes sense for \(\eta \geq 2\). However, in order to be able to pun about "crises of knowledge", the authors also define a ring version of the knowledge assumption. In the ring setting, they consider proper ideals rather than submodules.

** Cryptanalysis

The assumption is invalidated -- at least "morally" -- in [cite:@AC:WeeWu23]. Roughly speaking,  the attack uses that the preimages of \(g(\vec{v}) \cdot \vec{t}\) span a short basis of the submodule spanned by \(\vec{t}\): essentially an Ajtai-style trapdoor. Then, sampling an arbitrary, not-necessarily short, preimage of some \(c \cdot \vec{t}\), Babai rounding can be applied to obtain a short preimage of some other, random \(\tilde{c} \cdot \vec{t}\).

An implementation of the attack in SageMath is available [[https://gist.github.com/malb/7c8b86520c675560be62eda98dab2a6f][here]].

* Twin K-R-ISIS

[cite:@EPRINT:BCFL22]

#+begin_quote
let \(\vec{t} = (1,0,\ldots,0)\).
Let \(\mathcal{G}_{A}, \mathcal{G}_{B} \subset \mathcal{R}(\vec{X})\) be sets of \(w\)-variate Laurent monomial.
Let \((\mathcal{G}_{A} \cup \mathcal{G}_B)\) be k-M-ISIS-admissible.
Let \(\mat{A} \gets_{\$} \ring_q^{\eta \times \ell}\), \(\mat{B} \gets_{\$} \ring_q^{\eta \times \ell}\), \(\vec{v} \gets_{\$} (\ring_q^\star)^w\). The /Twin K-M-ISIS/ assumption states that given \((\mat{A}, \mat{B}, \{\vec{u}_{g}\}_{g \in \mathcal{G}_A}, \{\vec{w}_{g}\}_{g \in \mathcal{G}_B}, \vec{t}, \vec{v})\) with \(\vec{u}_{g}, \mathbf{w}_{g}\) short,
\[
g(\vec{v}) \cdot \vec{t} \equiv \mat{A}\cdot \vec{u}_{g} \bmod q,\ \forall\ g \in \mathcal{G}_{A},
\]
and
\[
g(\vec{v}) \cdot \vec{t} \equiv \mat{B}\cdot \vec{w}_{g} \bmod q,\ \forall\ g \in \mathcal{G}_{B}
\]
it is hard to find a short \(\vec{u}^{*}, \vec{w}^{*}\) s.t.
\[
\vec{0} \equiv \mat{A} \cdot \vec{u}^{*} +  \mat{B} \cdot \vec{w}^{*} \bmod q.
\]
#+end_quote

** Hardness

No detailed analysis is provided beyond ruling out overlapping sets \(\mathcal{G}_{A}\) and \(\mathcal{G}_{B}\) which would trivially solve the problem by outputting \((\vec{u}_g, -\vec{w}_g)\) as the solution.

* BASIS

[cite:@EC:WeeWu23]

We consider \(\mathsf{BASIS}\) with with \(k=2\), for simplicity.

#+begin_quote
Let \(\mat{A} \in \ZZ_{q}^{\eta \times \ell}\). We're given
\[\vec{B} := \begin{pmatrix}\mat{A}_{0} & \vec{0} & - \vec{G}_{\eta+1}\\
\vec{0} & \mat{A}_{1} & -\vec{G}_{\eta+1}\end{pmatrix}\] and a short \(\vec{T}\) s.t.
\[\vec{G}_{\eta'} \equiv \vec{B} \cdot \vec{T} \bmod q\]

We say \(\mathsf{BASIS}_{\mathsf{rand}}\) if \(\mat{A}_{i}\) are uniformly random for \(i>0\) and \(\mat{A}_{0} := [\mat{A} | \mat{A}^{T}]^{T}\) for some uniformly random \(\mat{A}\). and \(\mathsf{BASIS}_{\mathsf{struct}}\) when \(\mat{A}_{i} := \vec{W}_{i} \cdot \mat{A}\) for known \(\vec{W}_{i} \in \ZZ_{q}^{\eta \times \eta}\).

The \(\mathsf{BASIS}\) assumption states that given \((\vec{B}, \vec{T})\) it is hard to find a short \(\vec{x}\) s.t. \(\mat{A} \cdot \vec{x} \equiv \vec{0}\).
#+end_quote

** Hardness

It was shown in the original paper that \(\mathsf{BASIS}_{\mathsf{rand}}\) is as hard as SIS. The idea is that we can construct \(\vec{B}\) given \(\mat{A}\) since we can trapdoor all \(\mat{A}_{i}\) for \(i > 0\).

A way of looking at is by noting that for each column \(\vec{t} = (\vec{t}^{(0)}, \vec{t}^{(1)}, \vec{t}^{(G)})\) of \(\vec{T}\) we have \(\mat{A}_{i} \cdot \vec{t}^{(i)} \equiv \vec{G}_{\eta+1} \cdot \vec{t}^{(G)}\) where \(\vec{G}_{\eta+1} \cdot \vec{t}^{(G)}\) is close to uniform. Thus, we can sample \(\vec{t}^{(0)}\), compute \(\vec{y} := \mat{A}_{0} \cdot \vec{t}^{(0)}\) and then use the gadget structure of \(\vec{G}_{\eta+1}\) to find a short \(\vec{t}^{(G)}\) s.t. \(\mat{A}_{i} \cdot \vec{t}^{(i)} \equiv \vec{G}_{\eta+1} \cdot \vec{t}^{(G)}\). Then, using the trapdoors for \(\mat{A}_{i}\) with \(i>0\) we can find \(\vec{t}^{(i)}\) s.t. \(\mat{A}_{i} \cdot \vec{t}^{(i)} \equiv \vec{G}_{\eta+1} \cdot \vec{t}^{(G)}\).

The authors also show that given an algorithm for solving BASIS there is an algorithm for solving k-M-ISIS. This reduction outputs a BASIS instance of size \(k < \ell/k'\) where \(k'\) is the parameter \(k\) of the k-M-ISIS instance.

* PRISIS

PRISIS [cite:@EPRINT:FenNgu23] is a special case of BASIS. It is more structured than BASIS, so we might expect hardness results on PRISIS to translate to BASIS. It turns out the additional structure allows to prove a broader regime of parameters as hard as M-SIS.

#+begin_quote
Let \(\mat{A} \in \ring_{q}^{\eta \times \ell}\). We're given
\[\vec{B} := \begin{pmatrix}
\mat{A} &               \vec{0} & \cdots & - \vec{G}_{\eta+1}\\
\vec{0} &           w \cdot \mat{A} & \cdots & -\vec{G}_{\eta+1}\\
\mat{0} &               \vec{0} & \ddots & -\vec{G}_{\eta+1}\\
\vec{0} & \cdots & w^{\ell-1} \cdot \mat{A} & -\vec{G}_{\eta+1}
\end{pmatrix}\] and a short \(\vec{T}\) s.t.
\[\vec{G}_{\eta'} \equiv \vec{B} \cdot \vec{T} \bmod q.\]

The \(\mathsf{PRISIS}\) assumption states that given \((\mat{A}, \mat{B}, w, \vec{T})\) it is hard to find a short \(\vec{x}\) s.t. \(\mat{A} \cdot \vec{x} \equiv \vec{0}\).
#+end_quote

** Hardness

If \(\ell=2\) then PRISIS is no easier than M-SIS.

* ISISf

[cite:@EPRINT:BLNS23]

#+begin_quote
Let \(\mat{A} \in \ZZ_{q}^{\eta \times \ell}\) and let \(f: \ZZ_{N} \rightarrow \ZZ_{q}^{\eta}\) be a function. Given \((\mat{A}, f)\) and access to an oracle that when called samples a fresh \(x \sample \ZZ_{N}\) and outputs \(x, \vec{u}_{x}\) s.t. \[
\mat{A} \cdot \vec{u}_{x} \equiv f(x) \bmod q \text{ and } \|\vec{u}_{x}\| \leq \beta,
\]
the /ISISf/ assumption states that it is hard to output a fresh tuple \((x^{*}, \vec{u}^{*})\) s.t.
\[\mat{A} \cdot \vec{u}^{*} \equiv f(x^*) \bmod q \text{ and } \|\vec{u}^{*}\| \leq \beta^*.\]
#+end_quote

** Hardness

If \(f\) is a random oracle then the problem, in the ROM, is as hard as SIS.

In [cite:@EPRINT:BLNS23] the authors set \(f\) to be a function that first turns \(x \in \ZZ_{N}\) into a binary vector \(\vec{x} \in \{0,1\}^{\log N}\) and then outputs \(\mat{B} \cdot \vec{x}\). The call this problem \(ISIS_{bin}\). The authors analyse direct lattice reduction as well as exploiting relations on the image space. The authors also introduce an interactive variant and show its equivalence.

* COMMENT Evasive LWE

* Footer                                                                :ignore:

#+INCLUDE: footer.org

# Local Variables:
# eval: (typo-mode -1)
# eval: (org-cdlatex-mode 1)
# eval: (add-hook 'after-save-hook (lambda () (when (eq major-mode 'org-mode) (org-html-export-to-html))) nil t)
# End:
