#+TITLE: 17th IMA International Conference on Cryptography and Coding
#+OPTIONS: html-postamble:nil tex:t num:1
#+DESCRIPTION:
#+KEYWORDS:
#+SUBTITLE:
#+LATEX_HEADER:

*16 - 18 December 2019, St Anne’s College, University of Oxford*

* Updates

- 2019-08-13: Presentation Submission Deadline extended to *28 August, 6pm (UK time)*.
- 2019-07-24: Note that presentation submission will *open* on August 5 and *close* on August 14 (unchanged).
- 2019-07-12: Paper Submission Deadline extended to *19 July 2019, 6pm (UK Time)*.

* Important Dates
- *Submission Deadline:* 19 July 2019 (Papers) and 28 August 2019 (Presentations)
- *Author Notification:* 5 September 2019 (Papers) and 5 October 2019 (Presentations)
- *Proceedings Version Deadline:* 22 September 2019 (Papers)
- *Conference:* 16 to 18 December 2019

* Invited Talks

** [[https://people.cispa.io/cas.cremers/][Cas Cremers]]:

** [[https://cseweb.ucsd.edu/~nadiah/][Nadia Henninger]]:

** [[https://cmaurice.fr/][Clémentine Maurice]]: Side-channel Attacks on Microarchitecture: Beyond Crypto

Hardware is often considered as an abstract layer that behaves correctly, just executing instructions and outputing a result. However, the internal state of the hardware leaks information about the programs that are executing, paving the way for covert or side-channel attacks. Historically, cryptography has been a strong focus of research in the field of microarchitectural side-channel attacks However, the last years have shown a shift in the targets. During this presentation, we will review how microarchitectural attacks evolved in the last decade, and we will delve into side-channel attacks on keystroke timings as well as robust covert channels in the cloud.

** [[http://www.iscc.cnrs.fr/spip.php?article1980][Francesca Musiani]]: Nuancing the ‘User’ of Secure Messaging Tools

From 2016 to 2018, the H2020 NEXTLEAP (NEXT-generation Techno-Social and Legal Encryption, Access and Privacy) project has sought to ‘create, validate, and deploy communication and computation protocols that can serve as pillars for a secure, trust-worthy, annotable and privacy-respecting Internet that ensures citizens fundamental rights’. Its consortium included computer scientists and social scientists working in close interaction. In this talk, I will present some of the work that was conducted in the ‘social sciences-led’ strand of NEXTLEAP, which attempted to account for the diversity of users of secure messaging applications and their underlying protocols, as well as the different motivations of their developers.

Due to the increased deployment of secure messaging protocols in a variety of settings, differences between what developers “believe” are the needs of their users and their actual needs can have very tangible and potentially problematic consequences. Based on 90 interviews with both high and low-risk users, as well as the developers, of popular secure messaging applications, we mapped the design choices made by developers to threat models of both high-risk and low-risk users. Our research revealed interesting and sometimes surprising results, among which: high-risk users often consider client device seizures to be more dangerous than compromised servers; key verification is important to high-risk users, but they often do not engage in cryptographic key verification, instead using other “out of band” means; high-risk users, unlike low-risk users, often need pseudonyms and are heavily concerned over metadata collection. Developers tend to value open standards, open-source, and decentralization, but high-risk users often find these aspects less urgent given their more pressing concerns; and while, for developers, avoiding trusted third parties is an important concern, several high-risk users are in fact happy to rely on trusted third parties ‘protected’ by specific geo-political situations. We conclude by suggesting that work still needs to be done for secure messaging protocols to be aligned with real user needs, including high-risk, and with real-world threat models.


* Registration / Practical Information

See https://ima.org.uk/11167/17th-ima-international-conference-on-cryptography-and-coding/

* Calls

The mathematical theory and practice of both cryptography and coding underpins the provision of effective security and reliability for data communication, processing and storage. This seventeenth International Conference in an established and successful IMA series on the theme of "Cryptography and Coding" solicits original *research papers* and *presentations* on all technical aspects of cryptography and coding.

Submissions are welcome on any cryptographic or coding-theoretic topic including, but not limited to:

- Foundational theory and mathematics;
- The design, proposal, and analysis of cryptographic or coding primitives and protocols
- Secure implementation and optimisation in hardware or software; and
- Applied aspects of cryptography and coding.

** Call for Papers

The proceedings will be published in Springer's Lecture Notes in Computer Science series, and will be available at the conference.

Submissions must not substantially duplicate work that any of the authors has published elsewhere or has submitted in parallel to a journal or any other conference or workshop with proceedings. Accepted submissions may not appear in any other conference or workshop that has proceedings. Authors of accepted papers must guarantee that their paper will be presented at the conference and must make a full version of their paper available online.

All submissions will be blind-reviewed. Papers must be anonymous, with no author names, affiliations, acknowledgements, or obvious references. Submissions should begin with a cover page containing title, a short abstract, and a list of keywords. The body of the paper should be at most 14 pages, excluding the title page with abstract, the bibliography, and clearly marked appendices. Committee members are not required to review appendices, so the paper should be intelligible and self-contained within this length. The submission must be in [[https://www.springer.com/gb/computer-science/lncs/conference-proceedings-guidelines][Springer’s LNCS format]] (LaTeX). Submissions not meeting these guidelines risk rejection without consideration of their merits.

Submissions should be submitted via [[https://easychair.org/conferences/?conf=imacc2019][EasyChair]].

** Call for Presentations

The main criteria for acceptance are whether the committee believes that the proposed talk will be of interest and of appropriate quality to present to the IMACC audience:

Submissions must comply with the following rules:

- Submissions can be full papers (maximum 10 pages), abstracts (maximum 2 pages), or the expected presentation slides.
- Submissions must be non-anonymous and must clearly specify which author will give the talk.
- The submission should provide sufficient detail to explain what the talk will be about.

As these presentations do not enter the formal proceedings (see accompanying Call for Papers), we accept and encourage contributed talk proposals which correspond to papers that are under submission or already published elsewhere.

Presentations should be submitted via [[https://easychair.org/conferences/?conf=imacc2019][EasyChair]].

* Committees
** Programme Committee

- Adeline Roux-Langlois, Univ Rennes, CNRS, IRISA, France
- Alex Davidson, Cloudflare, UK
- Benjamin Dowling, Information Security Group, Royal Holloway, University of London, UK
- Caroline Fontaine, CNRS, France, LSV lab, France
- Carolyn Whitnall, University of Bristol, UK,
- Christian Janson, Technische Universität Darmstadt, Germany
- Christian Rechberger, TU Graz, Austria
- Christoph Striecks, AIT Austrian Institute of Technology, Austria
- Christophe Petit, School of Computer Science, University of Birmingham, UK
- Ciara Rafferty, Queen's University Belfast, UK
- Cong Ling, Imperial College London, UK
- Daniel Page, University of Bristol, UK
- Elizabeth Quaglia, Information Security Group, Royal Holloway, University of London, UK,
- Emmanuela Orsini, COSIC, KU Leuven, Belgium
- Julia Hesse, IBM Research - Zurich, Switzerland
- Martin Albrecht, Information Security Group, Royal Holloway, University of London, UK (*Chair*)
- Rachel Player, Information Security Group, Royal Holloway, University of London, UK
- Roope Vehkalahti, Aalto University, Finland
- Thyla van der Merwe, Mozilla, UK

** Steering Committee

- Liqun Chen, University of Surrey, UK
- Bahram Honary, School of Computing and Communication, University of Lancaster, UK
- Máire O'Neill, Centre for Secure Information Technologies, ECIT, Queen's University Belfast, UK
- Christopher Mitchell, Information Security Group, Royal Holloway University of London, UK
- Matthew Parker, Institute for Informatics, University of Bergen, Norway
- Kenneth Paterson, Information Security Group, Royal Holloway University of London, UK
- Fred Piper, UK
- Martijn Stam, Simula UiB, Norway

* Code of Conduct

We are committed to providing an experience free of harassment and discrimination at the IMA CCC conference, respecting the dignity of every participant.

If you experience harassment or discriminatory behavior at IMA CC, we encourage you to reach out to the Conference Chair Martin Albrecht or Ciara Rafferty.

Participants who violate this code may be sanctioned and/or expelled from the event, at the joint discretion of the Conference Chair and Ciara Rafferty. Any action will only be taken with the consent of the complaining party. UK law applies.

If you witness harassment or discriminatory behavior, please consider intervening.

* Further Information

For further details on the conference, please contact the IMA Conferences Department:\\
Email: [[mailto:conferences@ima.org.uk][conferences@ima.org.uk]]\\
Tel: +44 (0) 1702 354 020\\
Institute of Mathematics and its Applications, Catherine Richards House, 16 Nelson Street, Southend-on-Sea, Essex, SS1 1EF, UK

See also https://ima.org.uk/11167/17th-ima-international-conference-on-cryptography-and-coding/


# Local Variables:
# eval: (add-hook 'after-save-hook (lambda () (when (eq major-mode 'org-mode) (org-twbs-export-to-html))) nil t)
# End:
